# -*- coding: utf-8 -*-
"""Skil_t1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fHXIKN2imFN5vuc5j0bs2exUJE00FaKR
"""

import re

# Bjarni Þór Guðmundsson
# Btg7@hi.is

class Skil(object):
    """ Skiladaemi 1 f. REI """

    # Daemi 1
    def fun1(self, c):
        # Skrifa fall sem skilar reiknar hitastig i f gefid hitastig i c.
        f = c * 1.8 + 32
        return f

    # Daemi 2
    def fun2(self):
        # skila uppflettitoflu2
        d = {'a': 1,
             'b': 2,
             'c': [1, 2]}
        return d

    # Daemi 3
    def fun3(self, l):
        # skila fyrsta og sidasta staki i l sem lista k
        k = [l[0], l[-1]]
        return k

if __name__ == '__main__':
    skil = Skil()