# -*- coding: utf-8 -*-
"""skil_f1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vveQMw4pKuOikcINp4RQhuVhc9j88S_V
"""

class Skil(object):
    """Fyrirlestrardaemi 1 f. REI"""

    def fun1(self, n):
        ls = []
        if n % 2 == 0:
            for x in range(0, n + 1, 2):
                ls.append(x)
        else:
            for x in range(n, 0, -2):
                ls.append(x)
        return ls

if __name__ == '__main__':
    skil = Skil()